---
title: "STEM Data Wrangling"
author: "Erin Anthony"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Read in the data
```{r read in the data}
stem = read.csv("csv-data/all-data.csv")
```

### Examine the variable levels of the data selection variables
```{r examine the variable levels of the data selection variables}
levels(stem$HD2015.Undergraduate.offering) # remove "No undergraduate offering"
levels(stem$HD2015.Degree.granting.status) # remove "Nondegree-granting, primarily postsecondary"
levels(stem$HD2015.Institution.is.active.in.current.year) # remove missing values
levels(stem$IC2015.Bachelor.s.degree) # remove missing values, remove "Implied no", remove "Not applicable"
```

### Examine the variable levels of the independent variables
```{r examine the variable levels of the independent variables}
levels(stem$HD2015.Bureau.of.Economic.Analysis..BEA..regions) # categorical, remove missing values
levels(stem$HD2015.Historically.Black.College.or.University) # binary, remove missing values
levels(stem$HD2015.Tribal.college) # binary, remove missing values
levels(stem$HD2015.Degree.of.urbanization..Urban.centric.locale.) # categorical, remove missing values
levels(stem$IC2015.Open.admission.policy) # binary, remove missing values, remove "Not applicable"
levels(stem$HD2015.Land.Grant.Institution) # binary, remove missing values
levels(stem$IC2015.Associate.s.degree) # binary, remove missing values
levels(stem$IC2015.All.programs.offered.completely.via.distance.education) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.Undergraduate.programs.or.courses.are.offered.via.distance.education) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.Study.abroad) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.Weekend.evening..college) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.Remedial.services) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.Academic.career.counseling.service) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.Employment.services.for.students) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.Placement.services.for.completers) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.On.campus.day.care.for.students..children) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.Tuition.guaranteed.plan) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.Prepaid.tuition.plan) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.Tuition.payment.plan) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.Institution.provide.on.campus.housing) # binary, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015.Institution.provides.board.or.meal.plan) # binary, combine the two "Yes" levels, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$IC2015_AY.In.state.average.tuition.for.full.time.undergraduates) # ratio, remove missing values
levels(stem$IC2015_AY.Out.of.state.average.tuition.for.full.time.undergraduates) # ratio, remove missing values
levels(stem$HD2015.Institution.size.category) # categorical, remove missing values, remove "Not applicable", remove "Not reported"
levels(stem$EF2015D.Student.to.faculty.ratio) # ratio, remove missing values
levels(stem$SFA1415.Average.amount.of.federal..state..local..institutional.or.other.sources.of.grant.aid.awarded.to.undergraduate.students) # ratio, remove missing values
levels(stem$SFA1415.Average.amount.of.federal.student.loans.awarded.to.undergraduate.students) # ratio, remove missing values
```

### Examine the variable levels of the dependent variables
```{r examine the variable levels of the dependent variables}
levels(stem$DRVEF2015.Percent.of.undergraduate.enrollment.that.are.Black.or.African.American) # ratio, remove missing values
levels(stem$DRVEF2015.Percent.of.undergraduate.enrollment.that.are.Hispanic.Latino) # ratio, remove missing values
levels(stem$DRVGR2015.Graduation.rate...Bachelor.degree.within.6.years..Black..non.Hispanic) # ratio, remove missing values
levels(stem$DRVGR2015.Graduation.rate...Bachelor.degree.within.6.years..Hispanic) # ratio, remove missing values
```